### PR TITLE
Jeet.png

### PR DESCRIPTION
**Pull request by Delta0x33**

### CODE REVIEW

**Comment by sven-hash** [comment]
Need metadata nft

**Comment by Delta0x33** [comment]
I want to pish this logos to token info.

**Comment by sven-hash** [comment]
Please follow this and do one request
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by sven-hash** [comment]
Logo name must be in upper case

**Comment by sven-hash** [comment]
Logo name must be in upper case

**Pull request closed without merging**
