### PR TITLE
Rename remaining `tokens-meta` to `token-list`

### PR DESCRIPTION
**Pull request by tdroxler**
Resolves: #6

### CODE REVIEW

**Comment by tdroxler** [comment]
I add to increase the timeout to test the tokens metadata as it's on the edge of the default 5s timeout:

```
 ✕ validate token metadata (5001 ms)
...
✓ validate token metadata (4993 ms)
```

**Comment by tdroxler** [comment]
> I add to increase the timeout to test the tokens metadata as it's on the edge of the default 5s timeout:


Another solution could be [this one](https://github.com/alephium/token-list/pull/36/commits/1900a4dfe035c8f3314e5340bb1c31c65dd5727e) (tests are [passing on CI](https://github.com/alephium/token-list/pull/36))
The output is
image

Let me know which one you prefer

**Comment by tdroxler** [comment]
I thought about it this week-end and I think the second solution is better as the first one isn't future proof, it will fail again in few month. I'll push a new commit.

**Review by h0ngcha0 — APPROVED** [review]
LGMT :+1:

**Pull request merged**
