### PR TITLE
Update ALPA

### PR DESCRIPTION
**Pull request by kskqwe**

### CODE REVIEW

**Comment by sven-hash** [comment]
Please check error, and waiting on confirmation from FoxPool team

**Comment by sven-hash** [comment]
@kskqwe there's some errors, you need to have a token name and ticker when creating it

**Comment by kskqwe** [comment]
{
      "id": "1a4bfb04b85129fdff94d42369bdbda51d7d50c61b2c874adb137c19926aa203",
      "name": "ALPA",
      "symbol": "ALPA",
      "decimals": 2,
      "description": "FoxPool, the first MEME COIN issued by ALPH mining pool",
      "logoURI": "https://raw.githubusercontent.com/alephium/token-list/master/logos/ALPA.png"
    }
It seems I have filled it all out

**Comment by sven-hash** [comment]
Yes but when creating the tokens seems you missed the symbol

**Pull request merged**
