### PR TITLE
LOGIC

### PR DESCRIPTION
**Pull request by Fadkid1**
LOGIC TOKen

### CODE REVIEW

**Comment by Fadkid1** [comment]
> The image doesn't render, please check

Have uploaded three of it

**Comment by sven-hash** [comment]
Please resolve conflicts

**Comment by Fadkid1** [comment]
> Please resolve conflicts

how can i do that. i have done what i was supposed to do. Please check cause the image is rendering over here

**Comment by sven-hash** [comment]
Just click on resolve conflicts and adapt it

**Comment by diomark** [comment]
please resolve the conflicts (update mainnet.json again since there was a PR committed before yours) and resubmit. closing this one, please start over.

**Pull request closed without merging**
