### PR TITLE
Please verify the token

### PR DESCRIPTION
**Pull request by Alphrocks**
New token created for the same project, Alephium Rocks, as launch got aborted and compromised due to someone adding liquidity before launch time.
Thanks in advance

### CODE REVIEW

**Comment by sven-hash** [comment]
Please pull the last branch and resubmit your pr

**Comment by sven-hash** [comment]
One error left
https://github.com/alephium/token-list/actions/runs/8667438502/job/23770446806?pr=130

**Comment by sven-hash** [comment]
@Alphrocks can you check the error ?

**Comment by diomark** [comment]
@Alphrocks I think you need to re-base.

**Comment by not-reed** [comment]
image

Its because onchain there is a space at the end of the name "Rocks " and so it doesn't match the supplied json metadata "Rocks" (no space) and tests fail

**Pull request closed without merging**
