### PR TITLE
BEARZWIFGUNZ180042069 verify token

### PR DESCRIPTION
**Pull request by BearzWifGunz180042069**
Please verify BEARZWIFGUNZ180042069 onto the token list

### CODE REVIEW

**Comment by sven-hash** [comment]
Please fix the image path

**Comment by BearzWithGunz180042069** [comment]
> Please fix the image path

In which folder?

**Comment by BearzWifGunz180042069** [comment]
> Please fix the image path

Fixed - please verify when you can.

**Comment by BearzWifGunz180042069** [comment]
> > Please fix the image path
> 
> In which folder?

What is the error?

**Pull request closed without merging**
