### PR TITLE
Shiba SHIBBO

### PR DESCRIPTION
**Pull request by khank12**
Shiba

### CODE REVIEW

**Comment by sven-hash** [comment]
Please add an image

**Comment by khank12** [comment]
image added

**Comment by sven-hash** [comment]
Please do a new commit with the most recent token list

**Review by khank12 — COMMENTED** [review]
is anything else i forget to do?

**Comment by khank12** [comment]
Shiba

**Comment by diomark** [comment]
Had to revert this. please start over. the token info needs to be appended in mainnet.json not as it's own file.

**Review by khank12 — COMMENTED** [review]
6

**Pull request merged**
