### PR TITLE
token list dorkl 

### PR DESCRIPTION
**Pull request by steve42927**

### CODE REVIEW

**Comment by steve42927** [comment]
plesae confirm it

**Comment by sven-hash** [comment]
Resolve the conflicts and don't add the `.idea`

**Comment by steve42927** [comment]
whats your mean

**Comment by steve42927** [comment]
ok now？

**Comment by steve42927** [comment]
check please

**Comment by sven-hash** [comment]
Still not, idea folder is still there

**Comment by steve42927** [comment]
which one ，can you show me the screenshot？

**Comment by sven-hash** [comment]
Here
https://github.com/alephium/token-list/pull/275/files
And you need to resolve conflicts

**Comment by steve42927** [comment]
ok please check

**Comment by sven-hash** [comment]
please check the `.idea` folder, it's still there
I cannot merge if they are here

**Comment by steve42927** [comment]
which one ，i dont understand ，can you tell me

**Comment by steve42927** [comment]
how to fix it

**Comment by steve42927** [comment]
ok ，ithink now was ✅

**Comment by steve42927** [comment]
check please

**Comment by steve42927** [comment]
what happend

**Comment by steve42927** [comment]
whats wrong

**Comment by sven-hash** [comment]
Can you close the PR and redo it?

**Comment by steve42927** [comment]
ok

**Pull request closed without merging**
