### PR TITLE
JEET

### PR DESCRIPTION
**Pull request by hopsai**
Adding JEET - so that it is right

### CODE REVIEW

**Comment by Delta0x33** [comment]
Wtf

**Comment by Airdrophunt3110** [comment]
I think its right

**Comment by hopsai** [comment]
Not trying to insult anyone - Just trying to make sure that the decimals are correct and the description.  I saw a few failed attempts.  You wanted it in the token-list, so I figured I'd help out.

**Comment by sven-hash** [comment]
@Delta0x33 does the contract id is the same you have?

**Comment by diomark** [comment]
Contactid looks the same between this one and the previous pr. Any harm in merging?

**Pull request closed without merging**
